services:
  app:
    build:
      context: ./02_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./02_frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true