services:
  frontend:
    build:
      context: ./02_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./02_frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  backend:
    build:
      context: ./03_backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./03_backend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  postgres-dev:
    image: postgres:18-alpine
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb-dev
    ports:
      - 5432:5432
  postgres-test:
    image: postgres:18-alpine
    container_name: postgres-test
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb-test
    ports:
      - 5431:5432